### ISSUE TITLE
Non-ASCII chars in AS names are not displayed correctly

### ISSUE THREAD

**Issue by kloesing** [makepanic/globe#18]
Example:

http://globe.rndm.de/#/relay/A1DBFFEF396F770974F361C9FBAE42103FEBFC6C

More nodes in the same AS:

https://onionoo.torproject.org/details?as=28573

**Comment by makepanic** [comment]
Mh afaik it just displays what it gets from the onionoo api:

```
"as_name":"Servi\uFFFDos de Comunica\uFFFD\uFFFDo S.A.",
```

`\uFFFD` is a unicode [replacement character](http://www.fileformat.info/info/unicode/char/fffd/index.htm) and looks like `�`.

The `�` char is displayed on the globe page so i think there is nothing wrong.

```
'�' === '\uFFFD' // is true in JS
```

**Comment by kloesing** [comment]
Oh, you're right.  This is a problem in Onionoo, not in Globe.  Sorry for the noise!
