### ISSUE TITLE
Make "anonymous" a placeholder

### ISSUE THREAD

**Issue by gsathya** [makepanic/globe#29]
It makes sense to make "anonymous" a placeholder in the search input box. It sort of seems counter intuitive right now. And then maybe make "anonymous" the default, if the search string is empty?

**Comment by makepanic** [comment]
Globe now uses the placeholder attribute from the input element. 
We have #16 (Allow empty search string) to enable support for empty search strings.

**Comment by gsathya** [comment]
Excellent. Thanks!
