### ISSUE TITLE
Search by contact fails

### ISSUE THREAD

**Issue by kloesing** [makepanic/globe#36]
If I search for `sysdev {at} leap {dot} se` (which is an invalid search term to Onionoo), Globe attempts to search but never finishes.

**Comment by makepanic** [comment]
I fixed the loading indicator and added an error message. It's nearly the same notification that atlas displays. 

If that's ok I'm going to merge it.

Example: http://globe.rndm.de/canary/#/search/query=sysdev+%7Bat%7D+leap+%7Bdot%7D+se

**Comment by kloesing** [comment]
Looks good to me.  Thanks!
